<?xml version="1.0" encoding="UTF-8"?>

<project name="github-actions-deployment-poc" default="package" basedir=".">

    <property name="src.dir" value="src"/>
    <property name="build.dir" value="build"/>
    <property name="classes.dir" value="${build.dir}/classes"/>
    <property name="dist.dir" value="${build.dir}/dist"/>

    <target name="clean">
        <delete dir="${build.dir}"/>
    </target>

    <target name="compile">
        <mkdir dir="${classes.dir}"/>

        <javac
            srcdir="${src.dir}"
            destdir="${classes.dir}"
            includeantruntime="false"
        />
    </target>

    <target name="package" depends="clean,compile">

        <mkdir dir="${dist.dir}"/>

        <copy todir="${dist.dir}/config">
            <fileset dir="config"/>
        </copy>

        <copy todir="${dist.dir}/scripts">
            <fileset dir="scripts"/>
        </copy>

        <copy todir="${dist.dir}">
            <fileset dir="${classes.dir}"/>
        </copy>

        <jar
            destfile="${dist.dir}/application.jar"
            basedir="${classes.dir}"
        />

    </target>

</project>
